# Generated by Django 6.0.5 on 2026-05-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoustomerType',
            new_name='CustomerType',
        ),
    ]
